### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rrjanbiah** [whq731/swagger-mock-file-generator#1]
Is there any documentation on how to use `swaggerWithMock.json`?

(I'm looking for an automated way to test all API endpoints by detecting them and their params using Swagger JSON docs)

**Comment by rrjanbiah** [comment]
@whq731 Bump!

**Comment by whq731** [comment]
@rrjanbiah
Sorry for my late reply.
Hope this project can help you.
https://github.com/whq731/swagger-express-middleware-with-chance

**Comment by rrjanbiah** [comment]
@whq731 Thank you. Will check
